---
  1:
    - "Kelly's eye"
    - "At the beginning"
    - "Nelson's column"
  2:
    - "One little duck"
    - "Me and you"
  3:
    - "You and me"
    - "Cup of tea"
    - "One Little Flea"
  4:
    - "Knock at the door"
  5:
    - "Man alive"
  6:
    - "Tom's tricks"
    - "Tom Nix"
    - "Chopsticks"
  7:
    - "Lucky seven"
    - "God's in heaven"
  8:
    - "One Fat Lady"
    - "Golden gate"
  9:
    - "Doctor's orders"
  10:
    - "Tony's Den"
  11:
    - "Legs eleven"
  12:
    - "One dozen"
    - "One and two: a dozen"
    - "Monkey's cousin"
  13:
    - "Unlucky for some"
    - "Devil's number"
    - "Bakers dozen"
  14:
    - "Valentines day"
  15:
    - "Rugby team"
    - "Young and keen"
  16:
    - "Sweet sixteen"
    - "She's lovely"
    - "Never been kissed"
  17:
    - "Often been kissed"
    - "The age to catch 'em"
    - "Dancing Queen"
  18:
    - "Key of the door"
    - "Coming of age"
  19:
    - "Goodbye teens"
  20:
    - "Getting plenty"
    - "Blind twenty"
  21:
    - "Key of the door"
  22:
    - "Two little ducks"
    - "All the twos"
  23:
    - "Thee and me"
    - "The Lord is my Shepherd"
  24:
    - "Two dozen"
  25:
    - "Duck and dive"
  26:
    - "Bed and breakfast"
    - "Half a crown"
    - "Pick and mix"
  27:
    - "Little duck with a crutch"
    - "Gateway to heaven"
  28:
    - "In a state"
    - "Over weight"
  29:
    - "You're doing fine"
  30:
    - "Burlington Bertie"
    - "Dirty Gertie"
    - "Speed limit"
    - "Flirty thirty"
    - "Blind thirty"
  31:
    - "Get up and run"
  32:
    - "Buckle my Shoe"
  33:
    - "Dirty knees"
    - "All the threes"
    - "All the feathers"
    - "Two little fleas"
    - "Sherwood Forest"
  34:
    - "Ask for more"
  35:
    - "Jump and jive"
  36:
    - "Three dozen"
  37:
    - "A flea in heaven"
  38:
    - "Christmas cake"
  39:
    - "Those famous steps"
  40:
    - "Naughty Forty"
  41:
    - "Time for fun"
  42:
    - "That famous street in Manhattan"
    - "Whinny the Pooh"
  43:
    - "Down on your knees"
  44:
    - "Droopy drawers"
    - "All the fours"
  45:
    - "Halfway house"
    - "Halfway there"
  46:
    - "Up to tricks"
  47:
    - "Four and seven"
  48:
    - "Four dozen"
  49:
    - "PC (Police Constable)"
    - "Copper"
    - "Nick nick"
  50:
    - "Bulls eye"
    - "Blind fifty"
    - "Half a century"
  51:
    - "Tweak of the thumb"
  52:
    - "Weeks in a year"
    - "Danny La Rue"
  53:
    - "Stuck in the tree"
  54:
    - "Clean the floor"
  55:
    - "Snakes alive"
    - "All the fives"
  56:
    - "Was she worth it?"
  57:
    - "Heinz varieties"
  58:
    - "Make them wait"
    - "Choo choo Thomas"
  59:
    - "Brighton line"
  60:
    - "Three score"
    - "Blind sixty"
    - "Five dozen"
  61:
    - "Bakers bun"
  62:
    - "Tickety boo"
    - "Turn on the screw"
  63:
    - "Tickle me"
  64:
    - "Red raw"
    - "The Beatles number"
  65:
    - "Old age pension"
  66:
    - "Clickety click"
    - "All the sixes"
  67:
    - "Made in heaven"
    - "Argumentative number"
  68:
    - "Saving grace"
  69:
    - "The same both ways"
    - "your place or mine"
    - "Either way up"
    - "Meal for two"
  70:
    - "Three score and ten"
    - "Blind seventy"
  71:
    - "Bang on the drum"
  72:
    - "A crutch and a duck"
    - "Six dozen"
    - "Par for the course"
  73:
    - "Crutch and a flea"
    - "Queen Bee"
  74:
    - "Candy store"
  75:
    - "Strive and strive"
  76:
    - "Trombones"
  77:
    - "Sunset strip"
    - "All the sevens"
    - "Two little crutches"
  78:
    - "Heavens gate"
  79:
    - "One more time"
  80:
    - "Gandhi's breakfast"
    - "Blind eighty"
    - "Eight and blank"
  81:
    - "Fat lady and a little wee"
    - "Stop and run"
  82:
    - "Fat lady with a duck"
    - "Straight on through"
  83:
    - "Fat lady with a flea"
    - "Time for tea"
    - "Ethel's Ear"
  84:
    - "Seven dozen"
  85:
    - "Staying alive"
  86:
    - "Between the sticks"
  87:
    - "Fat lady with a crutch"
    - "Torquay in Devon"
  88:
    - "Two fat ladies"
    - "All the eights"
    - "Wobbly wobbly"
  89:
    - "Nearly there"
    - "All but one"
  90:
    - "Top of the shop"
    - "Top of the house"
    - "Blind ninety"
    - "End of the line"